# borrowed from https://github.com/goreleaser/homebrew-tap
language: objective-c
before_install:
  - brew update >/dev/null
script:
  - brew audit ./*.rb
  - brew install -v ./*.rb
  - brew test ./*.rb
